version: "3.8"

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - vscode-extensions:/root/.vscode-server/extensions
      - ./:/workspace
    command: tail -f /dev/null
  s3:
    image: adobe/s3mock:2.11.0
    ports:
      - "9090:9090"
    environment:
      initialBuckets: test

volumes:
  vscode-extensions:
